language: python
dist: bionic
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8" # current default Python on Travis CI

sudo: true
install:
  - export DISPLAY=:0  # workaround for pynput (for keyboard input) to import
  - pip install -r requirements.txt
script:
  - pytest
