language: python
sudo: false
git:
  depth: false

addons:
  apt:
    packages:
    - python-tk
    - python-sympy
    - python-tables 
    - locales 
    - wget 
    - gcc 
    - g++ 
    - build-essential 
    - libncurses-dev 
    - libpython-dev 
    - cython 
    - libx11-dev 
    - git 
    - flex
    - automake  
    - libtool  
    - libxext-dev 
    - libncurses-dev 
    - make
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8" # current default Python on Travis CI
install:
  - export DISPLAY=:0  # workaround for pynput (for keyboard input) to import
  - pip install -r requirements.txt
  - export PYTHONPATH=$PYTHONPATH:$TRAVIS_BUILD_DIR
script:
  - cd $TRAVIS_BUILD_DIR
  - python -m pytest
