language: python
sudo: true
git:
  depth: false

addons:
  apt:
    packages:
    - python-tk
    - python-sympy
    - python-tables 
    - locales 
    - wget 
    - gcc 
    - g++ 
    - build-essential 
    - libncurses-dev 
    - libpython-dev 
    - cython 
    - libx11-dev 
    - git 
    - flex 
    - automake  
    - libtool  
    - libxext-dev 
    - libncurses-dev 
    - make 
python:
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
install:
  - pip install -r requirements.txt
  - wget https://neuron.yale.edu/ftp/neuron/versions/v7.7/nrn-7.7.x86_64-linux.deb
  - sudo dpkg -i nrn-7.7.x86_64-linux.deb
  - export PYTHONPATH=$PYTHONPATH:/usr/local/nrn/lib/python/
script:
  - cd $TRAVIS_BUILD_DIR
  - python -m pytest
