# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        python-version: [3.6, 3.7]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: run
      run: |
        sudo apt install python-tk python-sympy python-tables locales wget gcc g++ build-essential libncurses-dev libpython-dev cython libx11-dev git flex automake libtool libxext-dev libncurses-dev make python3-matplotlib python3-seaborn python3-numpy python3-scipy python3-pandas bison python3-pytest
        wget https://neuron.yale.edu/ftp/neuron/versions/v7.7/nrn-7.7.x86_64-linux.deb
        sudo dpkg -i nrn-7.7.x86_64-linux.deb
        pip3 install pytest
        pip3 install -r requirements.txt
        export PYTHONPATH=$PYTHONPATH:/usr/local/nrn/lib/python/
        export PATH=$PATH:/usr/local/nrn/x86_64/bin
        python -m pytest

     
